Api
rpt09-mulder/gallery pull request #7
Opened 2018-12-20 06:30 UTC by jondionowens

Initial set up for getting JSON data
- additional db.js file handling connection to mLab db
- successfully returning JSON at localhost:3002/photos/:id
- some general restructuring of code base to be more modular

note: there will likely be some merge conflicts here. made a boo boo with the last PR

2018-12-20 18:09 UTC, allenhsieh requested changes
Hey, just did a quick pass in the morning. I'm going to leave it to @insivika or @kogisu to do final review and approval since i think i accidentally hogged the last 3 or 4 PRs

2018-12-20 18:09 UTC, allenhsieh commented on database/db.js
> +mongoose.connect(`mongodb://${process.env.DB_USER}:${process.env.DB_PASS}${process.env.DB_HOST}`);
One trick you can do is to stick the whole URI as a ENV variable, do you store 1 variable instead of 3
`mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost/rooms');`

2018-12-20 18:09 UTC, allenhsieh commented on database/db.js
> +const _ = require('lodash');
I notice you require lodash and bluebird but it doesn't seem to be used in this file

2018-12-20 18:09 UTC, allenhsieh commented on database/models.js
> +const PropertyModel = mongoose.model('Property');
I think you may be able to just export property on line 12 itself

2018-12-21 02:03 UTC, kogisu commented on database/db.js
> +mongoose.connect(`mongodb://${process.env.DB_USER}:${process.env.DB_PASS}${process.env.DB_HOST}`);
i agree with this.

2018-12-21 02:11 UTC, kogisu commented on database/db.js
> +const _ = require('lodash');
also promise, utils, readfile, models.

2018-12-21 02:45 UTC, jondionowens commented on database/db.js
> +mongoose.connect(`mongodb://${process.env.DB_USER}:${process.env.DB_PASS}${process.env.DB_HOST}`);
nice one, done

2018-12-21 02:47 UTC, jondionowens commented on database/db.js
> +const _ = require('lodash');
yeah, sloppy. done

2018-12-21 02:48 UTC, jondionowens commented on database/models.js
> +const PropertyModel = mongoose.model('Property');
right right. done

2018-12-21 02:51 UTC, jondionowens commented
@allenhsieh @kogisu Updates commited

2018-12-21 02:53 UTC, allenhsieh approved these changes
looks good for me, i'll let @kogisu do final review + squash and marge

2018-12-21 03:48 UTC, kogisu requested changes
Check this out

2018-12-21 03:48 UTC, kogisu commented on database/dbUtils.js
> +  queryPhotos: async function queryPhotos() {
there doesnt need to be an async here, or maybe just remove the function if you aren't using it

2018-12-21 05:46 UTC, merged